import type { DashboardData } from "./index";

export const demoDashboard: DashboardData = {
  month: "September 2026",
  period: { id: "period-sep-2026", startsOn: "2026-09-01", status: "active", carryoverCents: 125_000 },
  accounts: [
    { id: "cheque", name: "Everyday cheque", type: "cheque", role: "operational", purpose: "Primary income and known monthly expenses", mask: "•• 4242", currentBalanceCents: 784_250, creditLimitCents: null, includeInSafeToSpend: true, displayOrder: 1 },
    { id: "card-one", name: "Household card", type: "credit_card", role: "operational", purpose: "Groceries and utilities", mask: "•• 5588", currentBalanceCents: -184_200, creditLimitCents: 1_500_000, includeInSafeToSpend: true, displayOrder: 2 },
    { id: "daily-savings", name: "Daily savings", type: "savings", role: "operational", purpose: "Fuel and phone", mask: "•• 1111", currentBalanceCents: 312_400, creditLimitCents: null, includeInSafeToSpend: true, displayOrder: 3 },
    { id: "card-two", name: "Surplus card", type: "credit_card", role: "operational", purpose: "Month-end surplus and flexible spending", mask: "•• 9004", currentBalanceCents: -42_600, creditLimitCents: 800_000, includeInSafeToSpend: false, displayOrder: 4 },
    { id: "notice", name: "Notice savings", type: "savings", role: "savings", purpose: "Primary long-term savings", mask: "•• 2032", currentBalanceCents: 2_483_000, creditLimitCents: null, includeInSafeToSpend: false, displayOrder: 5 },
    { id: "loan-one", name: "Property loan A", type: "home_loan", role: "liability", purpose: "Mortgage for property one", mask: "•• 6101", currentBalanceCents: -128_450_000, creditLimitCents: null, includeInSafeToSpend: false, displayOrder: 6 },
    { id: "loan-two", name: "Property loan B", type: "home_loan", role: "liability", purpose: "Mortgage for property two", mask: "•• 7720", currentBalanceCents: -62_380_000, creditLimitCents: null, includeInSafeToSpend: false, displayOrder: 7 },
    { id: "rewards", name: "Bank rewards", type: "rewards", role: "rewards", purpose: "Rewards balance and redemptions", mask: "Points", currentBalanceCents: 15_450, creditLimitCents: null, includeInSafeToSpend: false, displayOrder: 8 },
  ],
  categories: [
    { id: "income", name: "Income", colour: "#C7F36B", icon: "wallet" },
    { id: "groceries", name: "Groceries", colour: "#D9F99D", icon: "basket" },
    { id: "transport", name: "Transport", colour: "#A5F3FC", icon: "car" },
    { id: "eating-out", name: "Eating out", colour: "#FDE68A", icon: "utensils" },
    { id: "home", name: "Home", colour: "#DDD6FE", icon: "home" },
    { id: "utilities", name: "Utilities", colour: "#FED7AA", icon: "zap" },
    { id: "insurance", name: "Insurance", colour: "#BFDBFE", icon: "shield" },
    { id: "savings-category", name: "Savings", colour: "#BBF7D0", icon: "landmark" },
    { id: "health", name: "Health", colour: "#FBCFE8", icon: "heart" },
    { id: "entertainment", name: "Entertainment", colour: "#C4B5FD", icon: "ticket" },
    { id: "fees", name: "Fees", colour: "#FECACA", icon: "receipt" },
    { id: "other", name: "Other", colour: "#D6D3D1", icon: "shapes" },
  ],
  budgets: [
    { id: "b1", categoryId: "groceries", limitCents: 420000, spentCents: 238450, committedCents: 23900 },
    { id: "b2", categoryId: "transport", limitCents: 180000, spentCents: 112800, committedCents: 17800 },
    { id: "b3", categoryId: "eating-out", limitCents: 140000, spentCents: 126500, committedCents: 0 },
    { id: "b4", categoryId: "home", limitCents: 600000, spentCents: 399965, committedCents: 0 },
  ],
  plannedItems: [
    { id: "p-income-1", direction: "income", kind: "income", name: "Salary", plannedCents: 6_400_000, actualCents: 6_400_000, accountId: "cheque", categoryId: "income", dueDay: 25, sortOrder: 1 },
    { id: "p-income-2", direction: "income", kind: "income", name: "Rental income", plannedCents: 650_000, actualCents: 650_000, accountId: "cheque", categoryId: "income", dueDay: 1, sortOrder: 2 },
    { id: "p-exp-1", direction: "expense", kind: "savings", name: "Long-term savings", plannedCents: 800_000, actualCents: 800_000, accountId: "notice", categoryId: "savings-category", dueDay: 25, sortOrder: 1 },
    { id: "p-exp-2", direction: "expense", kind: "fixed_expense", name: "Medical cover", plannedCents: 480_000, actualCents: 480_000, accountId: "cheque", categoryId: "insurance", dueDay: 1, sortOrder: 2 },
    { id: "p-exp-3", direction: "expense", kind: "debt_payment", name: "Property loan A", plannedCents: 1_650_000, actualCents: 1_650_000, accountId: "cheque", categoryId: "home", dueDay: 1, sortOrder: 3 },
    { id: "p-exp-4", direction: "expense", kind: "debt_payment", name: "Property loan B", plannedCents: 740_000, actualCents: 0, accountId: "cheque", categoryId: "home", dueDay: 10, sortOrder: 4 },
    { id: "p-exp-5", direction: "expense", kind: "variable_expense", name: "Groceries", plannedCents: 650_000, actualCents: 238_450, accountId: "card-one", categoryId: "groceries", dueDay: null, sortOrder: 5 },
    { id: "p-exp-6", direction: "expense", kind: "variable_expense", name: "Utilities", plannedCents: 320_000, actualCents: 185_000, accountId: "card-one", categoryId: "utilities", dueDay: 15, sortOrder: 6 },
    { id: "p-exp-7", direction: "expense", kind: "variable_expense", name: "Fuel", plannedCents: 250_000, actualCents: 112_800, accountId: "daily-savings", categoryId: "transport", dueDay: null, sortOrder: 7 },
    { id: "p-exp-8", direction: "expense", kind: "fixed_expense", name: "Phone", plannedCents: 90_000, actualCents: 90_000, accountId: "daily-savings", categoryId: "utilities", dueDay: 20, sortOrder: 8 },
    { id: "p-exp-9", direction: "expense", kind: "fixed_expense", name: "Insurance", plannedCents: 180_000, actualCents: 180_000, accountId: "cheque", categoryId: "insurance", dueDay: 3, sortOrder: 9 },
    { id: "p-exp-10", direction: "expense", kind: "fixed_expense", name: "Subscriptions", plannedCents: 65_000, actualCents: 22_900, accountId: "card-two", categoryId: "eating-out", dueDay: 12, sortOrder: 10 },
  ],
  transactions: [
    { id: "t1", accountId: "cheque", categoryId: "transport", occurredAt: "2026-09-11T07:42:00+02:00", amountCents: -17800, status: "pending", kind: "card_purchase", source: "sms", merchant: "City Ride", description: "Card reservation", needsReview: false, plannedItemIds: [] },
    { id: "t2", accountId: "cheque", categoryId: "groceries", occurredAt: "2026-09-10T17:18:00+02:00", amountCents: -84250, status: "posted", kind: "card_purchase", source: "sms", merchant: "Fresh Market", description: "Card purchase", needsReview: false, plannedItemIds: ["p-exp-5"] },
    { id: "t3", accountId: "cheque", categoryId: "home", occurredAt: "2026-09-10T06:00:00+02:00", amountCents: -399965, status: "posted", kind: "scheduled_payment", source: "sms", merchant: "Home loan", description: "Scheduled internal payment", needsReview: false, plannedItemIds: ["p-exp-3"] },
    { id: "t4", accountId: "cheque", categoryId: null, occurredAt: "2026-09-09T19:21:00+02:00", amountCents: -20000, status: "posted", kind: "transfer", source: "sms", merchant: "PayShap transfer", description: "External debit", needsReview: true, plannedItemIds: [] },
    { id: "t5", accountId: "cheque", categoryId: "eating-out", occurredAt: "2026-09-08T13:05:00+02:00", amountCents: -46500, status: "posted", kind: "card_purchase", source: "sms", merchant: "Corner Table", description: "Card purchase", needsReview: false, plannedItemIds: [] },
    { id: "t6", accountId: "card-one", categoryId: null, occurredAt: "2026-09-07T16:24:00+02:00", amountCents: -32990, status: "posted", kind: "card_purchase", source: "sms", merchant: "Neighbourhood Pharmacy", description: "Card purchase", needsReview: true, plannedItemIds: [] },
    { id: "t7", accountId: "card-two", categoryId: null, occurredAt: "2026-09-06T11:08:00+02:00", amountCents: -7500, status: "posted", kind: "card_purchase", source: "sms", merchant: "Station Parking", description: "Card purchase", needsReview: true, plannedItemIds: [] },
    { id: "t8", accountId: "cheque", categoryId: null, occurredAt: "2026-09-05T08:17:00+02:00", amountCents: -6800, status: "posted", kind: "card_purchase", source: "sms", merchant: "Morning Coffee", description: "Card purchase", needsReview: true, plannedItemIds: [] },
  ],
};
